### ISSUE TITLE
[Bug]: When trying to remove the other sessions, it doesn't delete sessions with the 'Remember Me' option.

### ISSUE THREAD

**Issue by jsamaniegog** [cjmellor/browser-sessions#6]
### What happened?

When trying to remove the other sessions, it doesn't delete sessions with the 'Remember Me' option.

### How to reproduce the bug

1. Log in on one browser.
2. Log in on another browser with the "remember me" option.
3. Execute BrowserSessions::logoutOtherBrowserSessions(); from the first browser.
4. Verify that the session has been removed from the table.
5. Refresh the page in the other browser and check if the session is still open.

### Package Version

1.0.0

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

Windows

**Comment by cjmellor** [comment]
`logoutOtherBrowserSessions` is a core Laravel function, so it likely is meant to function like this

**Comment by jsamaniegog** [comment]
I found a solution, simply set the remember_token field of the users table to NULL before calling logoutOtherDevices. Maybe you could include it in some way.

Thank you!!

**Comment by cjmellor** [comment]
I'm open to a PR for this. It would have to be optional though
